"""Emit ontology/scenario_orbat.ttl (the ABox) from data/scenario.py.

Contains the force structure (units, chain of command, nations, coalitions),
the platform individuals with their ontology type, AFSIM platform name and
AFSIM type individual (bs:simulationType), and
the platform-type loadouts (bs:canCarry).  Also validates that every platform
type and weapon type the simulation can emit is aligned to exactly one ontology
class in afsim_alignment.ttl.
"""
import sys
from pathlib import Path

from rdflib import Graph, Literal, Namespace, RDF, RDFS, URIRef

sys.path.insert(0, str(Path(__file__).parent))
import scenario as S  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
BS = Namespace("http://example.org/battlespace#")


def sim_name_index(tbox: Graph):
    """AFSIM type string -> (ontology classes, bs:SimulationType individual)."""
    idx, individual = {}, {}
    for ind, name in tbox.subject_objects(BS.simTypeName):
        individual[str(name)] = ind
        for cls in tbox.objects(ind, RDF.type):
            if cls != BS.SimulationType:
                idx.setdefault(str(name), []).append(cls)
    return idx, individual


def main():
    tbox = Graph().parse(ROOT / "ontology" / "battlespace.ttl").parse(ROOT / "ontology" / "afsim_alignment.ttl")
    idx, sim_type = sim_name_index(tbox)

    # ---- validation ----------------------------------------------------------
    problems = []
    used_weapons = set(S.WEAPON)
    for _, (_, _, _, _, loadout) in S.PTYPE.items():
        used_weapons |= set(loadout)
    for lo in S.LOADOUT_OVERRIDE.values():
        used_weapons |= set(lo)
    for name in sorted(used_weapons | set(S.PTYPE)):
        if len(idx.get(name, [])) != 1:
            problems.append(f"sim name {name!r} maps to {idx.get(name)}")
    if problems:
        raise SystemExit("ontology/scenario mismatch:\n  " + "\n  ".join(problems))

    def cls(sim_name):
        return idx[sim_name][0]

    g = Graph()
    g.bind("bs", BS)
    g.bind("rdfs", RDFS)

    for code, (label, coalition) in S.NATIONS.items():
        g.add((BS[code], RDF.type, BS.Nation))
        g.add((BS[code], RDFS.label, Literal(label)))
        g.add((BS[code], BS.memberOf, BS[coalition]))
    for code, (label, side) in S.COALITIONS.items():
        g.add((BS[code], RDF.type, BS.Coalition))
        g.add((BS[code], RDFS.label, Literal(label)))
        g.add((BS[code], BS.simSideName, Literal(side)))

    for root in (S.BLUE, S.RED):
        for unit, parent in S.iter_units(root):
            u = BS[f"unit_{unit.id}"]
            g.add((u, RDF.type, BS.MilitaryUnit))
            g.add((u, RDFS.label, Literal(unit.label)))
            g.add((u, BS.echelon, BS[unit.echelon]))
            g.add((u, BS.nation, BS[unit.nation]))
            g.add((u, BS.service, BS[unit.service]))
            if parent is not None:
                g.add((u, BS.directlySubordinateTo, BS[f"unit_{parent.id}"]))
        for callsign, ptype, unit, _side in S.iter_platforms(root):
            p = BS[f"plat_{callsign}"]
            g.add((p, RDF.type, cls(ptype)))
            g.add((p, RDFS.label, Literal(callsign)))
            g.add((p, BS.simPlatformName, Literal(callsign)))
            g.add((p, BS.simulationType, sim_type[ptype]))  # explicit link to its AFSIM type
            g.add((p, BS.assignedTo, BS[f"unit_{unit.id}"]))

    # loadouts: platform type -> munition types it carries in this scenario
    for root in (S.BLUE, S.RED):
        for callsign, ptype, _unit, _side in S.iter_platforms(root):
            loadout = S.LOADOUT_OVERRIDE.get(callsign, S.PTYPE[ptype][4])
            for w in loadout:
                g.add((cls(ptype), BS.canCarry, cls(w)))

    out = ROOT / "ontology" / "scenario_orbat.ttl"
    header = ("# Scenario order of battle for BALTIC SHIELD (ABox).\n"
              "# GENERATED by data/build_orbat_ttl.py from data/scenario.py - do not edit by hand.\n")
    out.write_text(header + g.serialize(format="turtle"), encoding="utf-8")
    print(f"wrote {out}: {len(g)} triples")


if __name__ == "__main__":
    main()
